  
version: "3.0"
services:
  mysql:
   image: mysql
   environment:
     MYSQL_ROOT_PASSWORD: pass
     MYSQL_DATABASE: DB
   volumes:
    - ./database:/var/lib/mysql
  web:
    build: frontend/
    ports:
     - 5000:80
    volumes:
     ##- ./frontend/html:/var/www/html/
     - "./front_end:/app"
     
